/**
 * A header file generated by I2C host driver.
 *
 * @file i2c_host_event_types.h
 *
 * @ingroup i2c_host_interrupt
 *
 * @brief This header file contains helper structures for the implementation of 
 *        the I2C host driver.
 *
 * @version I2C1 Driver Version 2.2.1
 * 
 * @version I2C1 Package Version 7.0.0
 */

/*
© [2025] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#ifndef I2C_EVENT_TYPES_H
#define	I2C_EVENT_TYPES_H

#include "i2c_host_types.h"

/**
 * @ingroup i2c_host_interrupt
 * @struct i2c_host_event_status_t
 * @brief Structure that defines the communication parameters for an I2C host.
 */
typedef struct
{
    bool busy; /**< A flag that signifies the host is currently busy */
    uint16_t address; /**< I2C client address */
    uint8_t *writePtr; /**< Pointer to the buffer used for transmission */
    size_t writeLength; /**< The number of bytes to be written or sent to the client */
    uint8_t *readPtr; /**< Pointer to the buffer for received data */
    size_t readLength; /**< Number of bytes to be read from the client */
    bool switchToRead; /**< Boolean flag to indicate switching to read mode */
    i2c_host_error_t errorState; /**< An instance of i2c_host_error_t */
} i2c_host_event_status_t;

extern volatile i2c_host_event_status_t i2c1Status;

#endif /* I2C_EVENT_TYPES_H */